In [127]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns 

In [128]:
Elect_dataset = pd.read_csv(r'C:\Users\tunde\Desktop\Hamoye Experience\Data_for_UCI_named.csv')

In [129]:
Elect_dataset['stabf'].value_counts()

unstable    6380
stable      3620
Name: stabf, dtype: int64

In [130]:
Elect_dataset.shape

(10000, 14)

In [131]:
Elect_dataset=Elect_dataset.drop(columns=['stab'])

In [132]:
Elect_dataset.isnull().any()

tau1     False
tau2     False
tau3     False
tau4     False
p1       False
p2       False
p3       False
p4       False
g1       False
g2       False
g3       False
g4       False
stabf    False
dtype: bool

In [133]:
import sklearn.utils
Elect_dataset = sklearn.utils.shuffle(Elect_dataset)
Elect_dataset = Elect_dataset.reset_index(drop= True )
Elect_dataset.shape
Elect_dataset.stabf.value_counts()

unstable    6380
stable      3620
Name: stabf, dtype: int64

In [134]:
X = Elect_dataset.drop(columns=['stabf'])
y = Elect_dataset['stabf']

In [135]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size= 0.2 , random_state= 1 )
y_train.value_counts()

unstable    5121
stable      2879
Name: stabf, dtype: int64

In [136]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train_balanced = scaler.fit_transform(x_train)

In [137]:
x_test = scaler.transform(x_test)

# Random Forest Classifier

In [138]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'gini', random_state = 1)
classifier.fit(x_train_balanced, y_train)

RandomForestClassifier(n_estimators=10, random_state=1)

In [139]:
y_pred =classifier.predict(x_test)

In [140]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(classifier, x_train_balanced, y_train, cv= 5 , scoring= 'f1_macro' )
scores

array([0.87771217, 0.87775593, 0.88615399, 0.85655297, 0.87595729])

In [141]:
from sklearn.metrics import recall_score, accuracy_score, precision_score, f1_score,confusion_matrix
cnf_mat = confusion_matrix(y_true=y_test, y_pred=y_pred, labels=[ 'stable' , 'unstable' ])

In [142]:
cnf_mat

array([[ 644,   97],
       [ 106, 1153]], dtype=int64)

In [143]:
accuracy = accuracy_score(y_true=y_test, y_pred=y_pred)
print( 'Accuracy: {}' .format(round(accuracy* 100 ), 2 ))

Accuracy: 90


In [144]:
precision = precision_score(y_true=y_test, y_pred=y_pred, pos_label= 'unstable' )
print( 'Precision: {}' .format(round(precision* 100 ), 2 ))

Precision: 92


In [145]:
recall = recall_score(y_true=y_test, y_pred=y_pred, pos_label= 'unstable' )
print( 'Recall: {}' .format(round(recall* 100 ), 2 ))

Recall: 92


In [146]:
f1 = f1_score(y_true=y_test, y_pred=y_pred, pos_label= 'unstable' )
print( 'F1: {}' .format(round(f1* 100 ), 2 ))

F1: 92


# Extral Trees Classifier

In [147]:
from sklearn.ensemble import ExtraTreesClassifier
classifier2 = ExtraTreesClassifier(random_state=1, n_estimators=500, criterion='gini', min_samples_split=2, min_samples_leaf=8,
                                  max_features='log2')
classifier2.fit(x_train_balanced,y_train)
y_pred2 = classifier2.predict(x_test)
y_pred2

array(['unstable', 'unstable', 'unstable', ..., 'stable', 'unstable',
       'unstable'], dtype=object)

In [148]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(classifier2, x_train_balanced, y_train, cv= 5 , scoring= 'f1_macro' )
scores

array([0.90121247, 0.88798254, 0.88595166, 0.87317692, 0.88769901])

In [149]:
from sklearn.metrics import recall_score, accuracy_score, precision_score, f1_score,confusion_matrix
cnf_mat = confusion_matrix(y_true=y_test, y_pred=y_pred2, labels=[ 'stable' , 'unstable' ])
cnf_mat

array([[ 566,  175],
       [  13, 1246]], dtype=int64)

In [150]:
accuracy = accuracy_score(y_true=y_test, y_pred=y_pred2)
print( 'Accuracy: {}' .format(round(accuracy* 100 ), 2 ))

Accuracy: 91


In [151]:
precision = precision_score(y_true=y_test, y_pred=y_pred2, pos_label= 'unstable' )
print( 'Precision: {}' .format(round(precision* 100 ), 2 ))

Precision: 88


In [152]:
recall = recall_score(y_true=y_test, y_pred=y_pred2, pos_label= 'unstable' )
print( 'Recall: {}' .format(round(recall* 100 ), 2 ))

Recall: 99


In [153]:
f1 = f1_score(y_true=y_test, y_pred=y_pred2, pos_label= 'unstable' )
print( 'F1: {}' .format(round(f1* 100 ), 2 ))

F1: 93


# Xgboost Model

In [154]:
import xgboost as xgb
from xgboost import XGBClassifier

xgboost = XGBClassifier(random_state=1)
xgb=xgboost.fit( x_train_balanced, y_train)
y_pred3 = xgb.predict(x_test)

In [155]:
y_pred3

array(['unstable', 'unstable', 'unstable', ..., 'stable', 'unstable',
       'unstable'], dtype=object)

In [156]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(xgb, x_train_balanced, y_train, cv= 5 , scoring= 'f1_macro' )
scores

array([0.91440661, 0.88546514, 0.90914572, 0.89481159, 0.90130047])

In [157]:
from sklearn.metrics import recall_score, accuracy_score, precision_score, f1_score,confusion_matrix
cnf_mat = confusion_matrix(y_true=y_test, y_pred=y_pred3, labels=[ 'stable' , 'unstable' ])
cnf_mat

array([[ 632,  109],
       [  53, 1206]], dtype=int64)

In [158]:
accuracy = accuracy_score(y_true=y_test, y_pred=y_pred3)
print( 'Accuracy: {}' .format(round(accuracy* 100 ), 4 ))

Accuracy: 92


In [159]:
precision = precision_score(y_true=y_test, y_pred=y_pred3, pos_label= 'unstable' )
print( 'Precision: {}' .format(round(precision* 100 ), 2 ))

Precision: 92


In [160]:
recall = recall_score(y_true=y_test, y_pred=y_pred3, pos_label= 'unstable' )
print( 'Recall: {}' .format(round(recall* 100 ), 2 ))

Recall: 96


In [161]:
f1 = f1_score(y_true=y_test, y_pred=y_pred2, pos_label= 'unstable' )
print( 'F1: {}' .format(round(f1* 100 ), 2 ))

F1: 93


In [162]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
y_trainlm = encoder.fit_transform(y_train)
y_testlm = encoder.transform(y_test)
y_testlm

array([1, 1, 1, ..., 0, 1, 1])

In [163]:
import lightgbm as lgb
train_data =lgb.Dataset(x_train_balanced,y_trainlm)
params = {'learning_rate':0.001}

In [164]:
lightm= lgb.train(params, train_data, 100) 

In [165]:
y_pred4 =lightm.predict(x_test)

In [166]:
y_pred4

array([0.65569111, 0.61830189, 0.63348743, ..., 0.59099051, 0.66978946,
       0.60689636])

# class sklearn.model_selection.RandomizedSearchCV(estimator, param_distributions, *, n_iter=10, scoring=None, n_jobs=None, iid='deprecated', refit=True, cv=None, verbose=0, pre_dispatch='2*n_jobs', random_state=None, error_score=nan, return_train_score=False)[source]

In [167]:
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import uniform
distributions = dict(C=uniform(loc=0, scale=4),
                     penalty=['l2', 'l1'])

In [168]:
clf = RandomizedSearchCV(classifier2, distributions, random_state=1,scoring='accuracy', cv=5, verbose=1,n_jobs=-1, n_iter=10,)